version: '3'

services:
  backend:
    build: './backend'
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"

  frontend:
    build: './frontend'
    depends_on:
      - backend
    ports:
      - 8080:8080
