version: '3'

services:
  backend:
    build: './backend'
    ports:
      - 8081:8081
    depends_on:
      - "db"

  db:
    image: postgres:latest
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: password

